# Generated by Django 2.2.4 on 2019-09-24 15:18

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='damsmcdagroup',
            options={'verbose_name': 'Dams MCDA Group', 'verbose_name_plural': 'Dams MCDA Groups'},
        ),
        migrations.AlterModelOptions(
            name='damsmcdauser',
            options={'verbose_name': 'Dams MCDA User', 'verbose_name_plural': 'Dams MCDA Users'},
        ),
        migrations.CreateModel(
            name='DamsMCDARunPreferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', django.contrib.postgres.fields.jsonb.JSONField()),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.DamsMCDAGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Run Preference',
                'verbose_name_plural': 'Run Preferences',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
