# Generated by Django 2.2.4 on 2019-09-24 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190924_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DamsMCDARunPreferences',
            new_name='DamsMCDARunPreference',
        ),
    ]
