# Generated by Django 2.2.4 on 2019-09-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190924_1541'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damsmcdarunpreference',
            unique_together=set(),
        ),
    ]
