# Generated by Django 2.2.4 on 2019-09-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190924_1625'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='damsmcdarunpreference',
            unique_together={('group', 'user')},
        ),
    ]
